### PR TITLE
upgrade rust version 1.33.0 to 1.42.0 to "error: enum variants on type aliases are experimental"

### PR DESCRIPTION
**Pull request by tomzhang**
here is the issue description:
when build docker with original Dockerfile that rust version is 1.33.0, which while panic the building process with below error message in the process of compiling  derive_builder_core v0.9.0 .
Compiling derive_builder_core v0.9.0
error: enum variants on type aliases are experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/derive_builder_core-0.9.0/src/initializer.rs:178:13
    |
178 |             Self::Move => tokens.append_all(quote!(
    |             ^^^^^^^^^^

error: enum variants on type aliases are experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/derive_builder_core-0.9.0/src/initializer.rs:181:13
    |
181 |             Self::Clone => tokens.append_all(quote!(
    |             ^^^^^^^^^^^

error: enum variants on type aliases are experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/derive_builder_core-0.9.0/src/initializer.rs:184:13
    |
184 |             Self::CloneNoStd => tokens.append_all(quote!(
    |             ^^^^^^^^^^^^^^^^

error: enum variants on type aliases are experimental
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/derive_builder_core-0.9.0/src/options.rs:26:18
   |
26 |         *self != Self::Owned
   |                  ^^^^^^^^^^^

error: enum variants on type aliases are experimental
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/derive_builder_core-0.9.0/src/options.rs:33:9
   |
33 |         Self::Mutable
   |         ^^^^^^^^^^^^^

error: aborting due to 5 previous errors

error: failed to compile `cargo-watch v7.3.0`, intermediate artifacts can be found at `/tmp/cargo-installTY2cgb`

Caused by:
  Could not compile `derive_builder_core`.
     Summary Failed to install cargo-audit, cargo-watch (see error(s) above).
error: some crates failed to install

---------------------------------------------------------------------------------
issue could be resolved with upgrade with rust version from 1.33 to 1.42

### CODE REVIEW

**Comment by acfoltzer** [comment]
Hi there, thank you for the PR! It looks like your patch is based on a very old commit from the `master` branch, 74a5e815ffa01d058d371a067ba38a47a034c8ba. The current `master` revision uses Rust 1.43.0. Are you able to use the newer revision?

**Comment by tomzhang** [comment]
@acfoltzer 
I will give it a try after then.
because what am doing its base on the installation README documents

**Comment by acfoltzer** [comment]
There were some slightly old instructions on https://bytecodealliance.github.io/lucet, but I have fixed those now. Those instructions were still much newer than the revision you are using on this branch, however. If there is a README pointing you to that old revision, could you please link it here so we can correct it?

**Comment by tomzhang** [comment]
this pull request can be close due to the reason that my copy branch is later than upstream/master.

**Pull request closed without merging**
