### PR TITLE
Update the minisign crate

### PR DESCRIPTION
**Pull request by jedisct1**
The version pinned in `lucet-module` didn't support modules larger than 1GB.

### CODE REVIEW

**Comment by jedisct1** [comment]
CI surfaced a security advisory for the `bumpalo` crate version we pinned.

Not a big security risk since it's only used by `criterion`, but this is breaking CI, so I just added an update for that one, too.

**Comment by fst-crenshaw** [comment]
@jedisct1 -- I don't see the criterion / bumpalo update on this PR.  Am I missing something?

**Comment by jedisct1** [comment]
@fst-crenshaw https://github.com/bytecodealliance/lucet/pull/461/commits/e6da5624d43eb2f2cb3c7554b8f65efc37f0e13a -- You need to click `view diff`.

**Comment by fst-crenshaw** [comment]
Thanks for the help.

**Pull request merged**
